W5D1/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :destroy, :new]

  resources :bands do
    resources :albums, only: [:new]
  end
  resources :albums, except: [:index, :new]
end

W5D1/music_app/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  year       :integer          not null
#  band_id    :integer          not null
#  studio     :boolean          default(TRUE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord
  validates :title, :year, :band_id, presence: true
  validates :studio, inclusion: { in: [true, false] }

  belongs_to :band

end

W5D1/music_app/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums
end

W5D1/music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, :password_digest, :session_token, presence: true
  validates :email, uniqueness: true
  validates :password, length: { minimum: 6 }, allow_nil: true
  after_initialize :ensure_session_token

  attr_reader :password

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

end

W5D1/music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def new
    @album = Album.new
    @band = Band.find_by(id: params[:band_id])
    @bands = Band.all
    render :new
  end

  def create
    @album = Album.new(album_params)
    @band = Band.find_by(id: params[:album][:band_id])
    @bands = Band.all
    if @album.save
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def update
    @album = Album.find(params[:id])
    if @album.update_attributes(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @band = @album.band
    if @album.destroy
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  private
  def album_params
    params.require(:album).permit(:title, :year, :band_id, :studio)
  end

end

W5D1/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def log_in_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def log_out_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    !current_user.nil?
  end

  def require_login
    unless logged_in?
      flash[:errors] = ["You must be logged in to view this page!"]
      redirect_to new_session_url
    end
  end

end

W5D1/music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController

  before_action :require_login

  def index
    @bands = Band.all
    render :index
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def update
    # Uses same partial as new
    @band = Band.find(params[:id])
    if @band.update_attributes(band_params)
      redirect_to band_url(@band)
    else
      flash_now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def edit
    # Uses partial
    @band = Band.find(params[:id])
    render :edit
  end

  def destroy
    @band = Band.find(params[:id])
    if @band.destroy
      redirect_to bands_url
    else
      flash.now[:errors] = ["Can't destroy band, band is too epic!"]
    end
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end

end

W5D1/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(user_params[:email], user_params[:password])
    if @user.nil?
      flash.now[:errors] = ["Invalid username or password!"]
      render :new
    else
      log_in_user!(@user)
      redirect_to user_url(@user)
    end
  end

  def destroy
    log_out_user!
    redirect_to new_session_url
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

W5D1/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in_user!(@user)
      # redirect_to user_url(@user)
      redirect_to bands_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def destroy
    @user.find_by(username: params[:username])
    if @user.destroy
      redirect_to new_session
    else
      flash.now[:errors] = @users.errors.full_messages
      render user_url(@user)
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end

end

W5D1/music_app/app/helpers/albums_helper.rb
module AlbumsHelper
end

W5D1/music_app/app/helpers/bands_helper.rb
module BandsHelper
end

W5D1/music_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

W5D1/music_app/app/helpers/users_helper.rb
module UsersHelper
end

W5D1/music_app/app/views/albums/_form.html.erb
<% action = (album.persisted? ? album_url(album) : albums_url) %>
<% method = (album.persisted? ? :patch : :post) %>

<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="title_name">Title</label>
  <input
    type="text"
    name="album[title]"
    id="title_name"
    value="<%= album.title %>">

  <br>

  <select class="" name="album[band_id]">
    <% @bands.each do |band_| %>
      <option value="<%= band.id %>"
      <%= "selected" if band_ == band %> >
        <%= band_.name %>
      </option>
    <% end %>
  </select>

  


  <% submit_text = (album.persisted? ? 'Update' : 'Create') + ' album!' %>
  <input type="submit" value="<%= submit_text %>">
</form>

W5D1/music_app/app/views/albums/new.html.erb
<section class="page"><div class="centered-box">
  <h1>New Album for <%= @band.name %> </h1>
  <%= render 'layouts/errors' %>
  <%= render 'form', album: @album, band: @band, bands: @bands %>
</div></section>

W5D1/music_app/app/views/bands/_form.html.erb
<% action = (band.persisted? ? band_url(band) : bands_url) %>
<% method = (band.persisted? ? :patch : :post) %>

<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="band_name">Name</label>
  <input
    type="text"
    name="band[name]"
    id="band_name"
    value="<%= band.name %>">

  <br>

  <% submit_text = (band.persisted? ? 'Update' : 'Create') + ' band!' %>
  <input type="submit" value="<%= submit_text %>">
</form>

W5D1/music_app/app/views/bands/edit.html.erb
<section class="page"><div class="centered-box">
  <h1>Edit Band</h1>
  <%= render 'layouts/errors' %>
  <%= render 'form', band: @band %>
</div></section>

W5D1/music_app/app/views/bands/index.html.erb
<h2>All of the bands!</h2>

<%= link_to "Add a band!", new_band_url %>

<br><br><br>

<section class="band-index">
   <% @bands.each.with_index do |band, i| %>
     <div class="band-index-item">
       <div>
         <img src="http://lorempixel.com/300/300/abstract/<%=i%>" >
         <%= band.name %>
         <%= button_to "Update", edit_band_url(band.id), method: :get %>
         <%= button_to "Delete", band_url(band.id), method: :delete %>
       </div>
     </div>
   <% end %>
 </section>

W5D1/music_app/app/views/bands/new.html.erb
<section class="page"><div class="centered-box">
  <h1>New Band</h1>
  <%= render 'layouts/errors' %>
  <%= render 'form', band: @band %>
</div></section>

W5D1/music_app/app/views/bands/show.html.erb
<h2> Showing information for <%= @band.name %>! </h2>
<img src="http://lorempixel.com/300/300/abstract/" alt="cover">

<%= button_to "Back", bands_url, method: :get %>

W5D1/music_app/app/views/layouts/_errors.html.erb
<% if flash.now[:errors] %>
  <% flash.now[:errors].each do |error| %>
   <%= error %><br />
  <% end %>
<% end %>

W5D1/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <h1>
      MUSIC APP
    </h1>

    <% if current_user %>
      <%= button_to "SIGN OUT", session_url, method: :delete, class: "sign" %>
    <% end %>

    <%= yield %>
  </body>
</html>

W5D1/music_app/app/views/users/new.html.erb
<h2>NEW USER</h2>
<%= link_to "SIGN IN", new_session_url, class: "sign" %>
<%= render partial: 'layouts/errors' %>

<br><br>
<form action="<%= users_url %>" method="post">

  <input id = "email" type="text" name="user[email]" placeholder="Email">

  <br><br>

  <input id="password" type="password" name="user[password]" placeholder="Password">

  <br><br>

  <input type="submit" value="Submit">

</form>

W5D1/music_app/app/views/users/show.html.erb
<h2> WELCOME BACK <%= @user.email %> </h2>